[2025-10-19T21:37:03.804+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-19T21:37:03.841+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:37:01.943160+00:00 [queued]>
[2025-10-19T21:37:03.860+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:37:01.943160+00:00 [queued]>
[2025-10-19T21:37:03.862+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-10-19T21:37:03.885+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_training_pipeline> on 2025-10-19 21:37:01.943160+00:00
[2025-10-19T21:37:03.898+0000] {standard_task_runner.py:72} INFO - Started process 551 to run task
[2025-10-19T21:37:03.906+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_model_retraining', 'run_training_pipeline', 'manual__2025-10-19T21:37:01.943160+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/weekly_retrain_dag.py', '--cfg-path', '/tmp/tmpuge15tpu']
[2025-10-19T21:37:03.913+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_training_pipeline
[2025-10-19T21:37:04.075+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:37:01.943160+00:00 [running]> on host 04677cc6273c
[2025-10-19T21:37:04.240+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='team@example.com' AIRFLOW_CTX_DAG_OWNER='ml-team' AIRFLOW_CTX_DAG_ID='weekly_model_retraining' AIRFLOW_CTX_TASK_ID='run_training_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T21:37:01.943160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T21:37:01.943160+00:00'
[2025-10-19T21:37:04.242+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-19T21:37:04.308+0000] {docker.py:379} INFO - Starting docker container from image fraud-detection:latest
[2025-10-19T21:37:09.968+0000] {docker.py:73} INFO - Traceback (most recent call last):
[2025-10-19T21:37:09.969+0000] {docker.py:73} INFO -   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-10-19T21:37:09.970+0000] {docker.py:73} INFO -   File "<frozen runpy>", line 88, in _run_code
[2025-10-19T21:37:09.971+0000] {docker.py:73} INFO -   File "/app/scripts/run_pipeline.py", line 8, in <module>
[2025-10-19T21:37:09.972+0000] {docker.py:73} INFO -     import mlflow
[2025-10-19T21:37:09.973+0000] {docker.py:73} INFO - ModuleNotFoundError: No module named 'mlflow'
[2025-10-19T21:37:11.539+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-10-19T21:37:11.548+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weekly_model_retraining, task_id=run_training_pipeline, run_id=manual__2025-10-19T21:37:01.943160+00:00, execution_date=20251019T213701, start_date=20251019T213703, end_date=20251019T213711
[2025-10-19T21:37:11.569+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-19T21:37:11.570+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_training_pipeline (Docker container failed: {'StatusCode': 1}; 551)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-10-19T21:37:11.617+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-19T21:37:11.638+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-19T21:37:11.644+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
