[2025-10-19T21:46:12.826+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-19T21:46:12.856+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:45:49.097875+00:00 [queued]>
[2025-10-19T21:46:12.866+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:45:49.097875+00:00 [queued]>
[2025-10-19T21:46:12.867+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-10-19T21:46:12.885+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): run_training_pipeline> on 2025-10-19 21:45:49.097875+00:00
[2025-10-19T21:46:12.892+0000] {standard_task_runner.py:72} INFO - Started process 841 to run task
[2025-10-19T21:46:12.896+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_model_retraining', 'run_training_pipeline', 'manual__2025-10-19T21:45:49.097875+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/weekly_retrain_dag.py', '--cfg-path', '/tmp/tmpt16u62tj']
[2025-10-19T21:46:12.901+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_training_pipeline
[2025-10-19T21:46:12.983+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_model_retraining.run_training_pipeline manual__2025-10-19T21:45:49.097875+00:00 [running]> on host 04677cc6273c
[2025-10-19T21:46:13.103+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='team@example.com' AIRFLOW_CTX_DAG_OWNER='ml-team' AIRFLOW_CTX_DAG_ID='weekly_model_retraining' AIRFLOW_CTX_TASK_ID='run_training_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T21:45:49.097875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T21:45:49.097875+00:00'
[2025-10-19T21:46:13.107+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-19T21:46:13.183+0000] {docker.py:379} INFO - Starting docker container from image fraud-detection:latest
[2025-10-19T21:46:16.155+0000] {docker.py:73} INFO - 2025/10/19 21:46:16 INFO mlflow.tracking.fluent: Experiment with name 'Fraud Detection' does not exist. Creating a new experiment.
[2025-10-19T21:46:56.542+0000] {docker.py:73} INFO - 2025/10/19 21:46:56 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-10-19T21:46:56.547+0000] {docker.py:73} INFO - The git executable must be specified in one of the following ways:
[2025-10-19T21:46:56.548+0000] {docker.py:73} INFO -     - be included in your $PATH
[2025-10-19T21:46:56.549+0000] {docker.py:73} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-10-19T21:46:56.550+0000] {docker.py:73} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-10-19T21:46:56.551+0000] {docker.py:73} INFO - 
[2025-10-19T21:46:56.553+0000] {docker.py:73} INFO - All git commands will error until this is rectified.
[2025-10-19T21:46:56.555+0000] {docker.py:73} INFO - 
[2025-10-19T21:46:56.559+0000] {docker.py:73} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-10-19T21:46:56.562+0000] {docker.py:73} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-10-19T21:46:56.564+0000] {docker.py:73} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-10-19T21:46:56.565+0000] {docker.py:73} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-10-19T21:46:56.566+0000] {docker.py:73} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-10-19T21:46:56.568+0000] {docker.py:73} INFO - 
[2025-10-19T21:46:56.569+0000] {docker.py:73} INFO - Example:
[2025-10-19T21:46:56.570+0000] {docker.py:73} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-10-19T21:46:57.359+0000] {docker.py:73} INFO - /usr/local/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [21:46:57] WARNING: /workspace/src/learner.cc:740: 
[2025-10-19T21:46:57.364+0000] {docker.py:73} INFO - Parameters: { "use_label_encoder" } are not used.
[2025-10-19T21:46:57.369+0000] {docker.py:73} INFO - 
[2025-10-19T21:46:57.372+0000] {docker.py:73} INFO -   warnings.warn(smsg, UserWarning)
[2025-10-19T21:47:37.066+0000] {docker.py:73} INFO - Successfully registered model 'fraud_detection_xgboost'.
[2025-10-19T21:47:37.255+0000] {docker.py:73} INFO - 2025/10/19 21:47:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: fraud_detection_xgboost, version 1
[2025-10-19T21:47:37.256+0000] {docker.py:73} INFO - Created version '1' of model 'fraud_detection_xgboost'.
[2025-10-19T21:47:37.275+0000] {docker.py:73} INFO - 2025/10/19 21:47:37 INFO mlflow.tracking._tracking_service.client: üèÉ View run xgboost_smote_20251019_214656 at: http://mlflow-server:5000/#/experiments/1/runs/09e9028ec1df40a2a59feeb8e09b920b.
[2025-10-19T21:47:37.276+0000] {docker.py:73} INFO - 2025/10/19 21:47:37 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-server:5000/#/experiments/1.
[2025-10-19T21:47:37.313+0000] {docker.py:73} INFO - ‚úÖ Done | ROC-AUC: 0.0000 | http://mlflow-server:5000
[2025-10-19T21:47:38.566+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-19T21:47:38.568+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weekly_model_retraining, task_id=run_training_pipeline, run_id=manual__2025-10-19T21:45:49.097875+00:00, execution_date=20251019T214549, start_date=20251019T214612, end_date=20251019T214738
[2025-10-19T21:47:38.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-19T21:47:38.698+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-19T21:47:38.703+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
